<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1">        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> 
        <link rel="stylesheet" href="./admin.css" />
<div class="container">
        </head>
        <body>
            <section class="content inbox"> <div class="container-fluid"> <div class="row clearfix"> <div class="col-lg-12"> <div class="card action_bar"> <div class="body"> <div class="row clearfix"> <div class="col-lg-1 col-md-2 col-3">
                <div class="checkbox inlineblock delete_all">
                <input id="deleteall" type="checkbox">
            <label for="deleteall"> All </label>
            </div>
            </div>
            <div class="col-lg-5 col-md-4 col-6">
                <div class="input-group search"> <input type="text" class="form-control" placeholder="Search...">
                <span class="input-group-addon">
                    <a class="btn btn-primary" href="#" role="button">Search</a>
                    </span>
                    </div>
                    </div>
                    </div>
                    </div> </div> </div> </div> <div class="row clearfix"> <div class="col-md-12 col-lg-12 col-xl-12">
                <ul class="mail_list list-group list-unstyled">
                    <li class="list-group-item"> <div class="media">
                        <div class="pull-left"> <div class="controls">
                            <div class="checkbox"> <input type="checkbox" id="basic_checkbox_1">
                            <label for="basic_checkbox_1"></label>
                            </div>
                            <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                <i class="zmdi zmdi-star-outline"></i>
                                </a>
                                </div>
                                <div class="thumb hidden-sm-down m-r-20">
                                    <img src="assets/images/xs/avatar1.jpg" class="rounded-circle" alt="">
                                    </div>
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading">
                                             <a href="mail-single.html" class="m-r-10">Naruto Uzumaki</a>
                                        </a> <span class="badge bg-green">Jobseeker</span>
                                        <small class="float-right text-muted">
                                            <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                       <i class="zmdi zmdi-attachment-alt"></i> </small> </div> <p class="msg">Request for account Verification...</p>
                                            </div>
                                            </div>
                                            </li> <li class="list-group-item unread"> <div class="media">
                                                <div class="pull-left">
                                                    <div class="controls">
                                                        <div class="checkbox">
                                                            <input type="checkbox" id="basic_checkbox_2"> <label for="basic_checkbox_2">                                                                                                            </label>
                                                            </div>
                                                            <a href="javascript:void(0);" class="favourite col-amber hidden-sm-down" data-toggle="active">
                                                                <i class="zmdi zmdi-star"></i></a> </div> <div class="thumb hidden-sm-down m-r-20"> <img src="assets/images/xs/avatar2.jpg" class="rounded-circle" alt=""> </div> </div> <div class="media-body">
                                                                    <div class="media-heading">
                                                                        <a href="mail-single.html" class="m-r-10">Uchiha Itatchi</a>
                                                                <span class="badge bg-green">Jobseekeer</span> <small class="float-right text-muted">
                                                                    <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                    <i class="zmdi zmdi-attachment-alt"></i> </small> </div> <p class="msg">Request for Account Verification.</p>
                                                                    </div>
                                                                    </div>
                                                                    </li>
                                                                    <li class="list-group-item">
                                                                        <div class="media">
                                                                            <div class="pull-left">
                                                                                <div class="controls">
                                                                                    <div class="checkbox">
                                                                                        <input type="checkbox" id="basic_checkbox_3"> <label for="basic_checkbox_3"></label>
                                                                                        </div> <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                                                                            <i class="zmdi zmdi-star-outline"></i>
                                                                                            </a>
                                                                                             </div>
                                                                                             <div class="thumb hidden-sm-down m-r-20"> <img src="assets/images/xs/avatar3.jpg" class="rounded-circle" alt="">
                                                                                             </div>
                                                                                             </div>
                                                                                             <div class="media-body">
                                                                                                 <div class="media-heading">
                                                                                                 <a href="mail-single.html" class="m-r-10">Hidden Leaf Inc.</a>
                                                                <span class="badge bg-blush">Employer</span> <small class="float-right text-muted">
                                                                    <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                    <i class="zmdi zmdi-attachment-alt"></i> </small> </div> <p class="msg">Request for Account Verification.</p>
                                                                                                 </div>
                                                                                                 </div>
                                                                                                 </li>
                                                                                                 <li class="list-group-item unread">
                                                                                                     <div class="media">
                                                                                                         <div class="pull-left">
                                                                                                             <div class="controls">
                                                                                                                 <div class="checkbox">
                                                                                                                     <input type="checkbox" id="basic_checkbox_4"> <label for="basic_checkbox_4"></label>
                                                                                                                     </div>
                                                                                                                     <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                                                                                                         <i class="zmdi zmdi-star-outline"></i>
                                                                                                                         </a>
                                                                                                                         </div>
                                                                                                                         <div class="thumb hidden-sm-down m-r-20">
                                                                                                                             <img src="assets/images/xs/avatar4.jpg" class="rounded-circle" alt="">
                                                                                                                             </div>
                                                                                                                             </div>
                                                                                                                             <div class="media-body">
                                                                                                                                 <div class="media-heading"> <a href="mail-single.html" class="m-r-10">Secret Police Inc.</a> <span class="badge bg-blush">Employer</span>
                                                                                                                                 <small class="float-right text-muted">
                                                                                                                                     <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                     <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                     </small>
                                                                                                                                     </div>
                                                                                                                                     <p class="msg">Request for Account Verification </p>
                                                                                                                                     </div>
                                                                                                                                     </div>
                                                                                                                                     </li>
                                                                                                                                     <li class="list-group-item">
                                                                                                                                         <div class="media">
                                                                                                                                             <div class="pull-left">
                                                                                                                                                 <div class="controls">
                                                                                                                                                     <div class="checkbox">
                                                                                                                                                         <input type="checkbox" id="basic_checkbox_5"> <label for="basic_checkbox_5"></label>
                                                                                                                                                         </div>
                                                                                                                                                         <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                                                                                                                                             <i class="zmdi zmdi-star-outline"></i>
                                                                                                                                                             </a>
                                                                                                                                                             </div>
                                                                                                                                                             <div class="thumb hidden-sm-down m-r-20">
                                                                                                                                                                 <img src="assets/images/xs/avatar5.jpg" class="rounded-circle" alt="">
                                                                                                                                                                 </div>
                                                                                                                                                                 </div>
                                                                                                                                                                 <div class="media-body">
                                                                                                                                                                     <div class="media-heading">
                                                                                                                                                                         <a href="mail-single.html" class="m-r-10">Loid Forger</a> <span class="badge bg-green">Jobseeker</span>
                                                                                                                                                                         <small class="float-right text-muted">
                                                                                                                                                                             <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                             <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                             </small>
                                                                                                                                                                             </div>
                                                                                                                                                                             <p class="msg">Request for Account Verification</p>
                                                                                                                                                                             </div>
                                                                                                                                                                             </div>
                                                                                                                                                                             </li>
                                                                                                                                                                             <li class="list-group-item">
                                                                                                                                                                                 <div class="media">
                                                                                                                                                                                     <div class="pull-left">
                                                                                                                                                                                         <div class="controls">
                                                                                                                                                                                             <div class="checkbox">
                                                                                                                                                                                                 <input type="checkbox" id="basic_checkbox_6"> <label for="basic_checkbox_6"></label>
                                                                                                                                                                                                 </div>
                                                                                                                                                                                                 <a href="javascript:void(0);" class="favourite col-amber hidden-sm-down" data-toggle="active">
                                                                                                                                                                                                     <i class="zmdi zmdi-star"></i>
                                                                                                                                                                                                     </a>
                                                                                                                                                                                                     </div>
                                                                                                                                                                                                     <div class="thumb hidden-sm-down m-r-20"> <img src="assets/images/xs/avatar6.jpg" class="rounded-circle" alt="">
                                                                                                                                                                                                     </div>
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                       <div class="media-body">
                                                                                                                                                                                                           <div class="media-heading">
                                                                                                                                                                                                               <a href="mail-single.html" class="m-r-10">Eren Jeagar</a>
                                                                                                                                                                                                               <span class="badge bg-green">Jobseeker</span> <small class="float-right text-muted">
                                                                                                                                                                                                                   <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                                                                   <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                                                                   </small>
                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                   <p class="msg">Request for Account Verification</p>
                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                    <li class="list-group-item">
                                                                                                                                                                                                                        <div class="media">
                                                                                                                                                                                                                            <div class="pull-left">
                                                                                                                                                                                                                                <div class="controls">
                                                                                                                                                                                                                                    <div class="checkbox">
                                                                                                                                                                                                                                        <input type="checkbox" id="basic_checkbox_7"> <label for="basic_checkbox_7"></label>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                        <a href="javascript:void(0);" class="favourite col-amber hidden-sm-down" data-toggle="active">
                                                                                                                                                                                                                                            <i class="zmdi zmdi-star"></i>
                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                            <div class="thumb hidden-sm-down m-r-20">
                                                                                                                                                                                                                                                <img src="assets/images/xs/avatar7.jpg" class="rounded-circle" alt="">
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                 <div class="media-body">
                                                                                                                                                                                                                                                     <div class="media-heading">
                                                                                                                                                                                                                                                         <a href="mail-single.html" class="m-r-10">Jujutsu Corp.</a>
                                                                                                                                                                                                                                                         <span class="badge bg-blush">Employer</span> <small class="float-right text-muted">
                                                                                                                                                                                                                                                             <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                                                                                                             <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                                                                                                             </small>
                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                             <p class="msg">Request for Account Verification </p>
                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                             </li>
                                                                                                                                                                                                                                                             <li class="list-group-item">
                                                                                                                                                                                                                                                                 <div class="media">
                                                                                                                                                                                                                                                                     <div class="pull-left">
                                                                                                                                                                                                                                                                         <div class="controls">
                                                                                                                                                                                                                                                                             <div class="checkbox">
                                                                                                                                                                                                                                                                                 <input type="checkbox" id="basic_checkbox_8" checked="">
                                                                                                                                                                                                                                                                                 <label for="basic_checkbox_8"></label>
                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                 <a href="javascript:void(0);" class="favourite col-amber hidden-sm-down" data-toggle="active">
                                                                                                                                                                                                                                                                                     <i class="zmdi zmdi-star"></i>
                                                                                                                                                                                                                                                                                     </a>
                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                     <div class="thumb hidden-sm-down m-r-20"> <img src="assets/images/xs/avatar8.jpg" class="rounded-circle" alt="">
                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                     <div class="media-body">
                                                                                                                                                                                                                                                                                         <div class="media-heading">
                                                                                                                                                                                                                                                                                             <a href="mail-single.html" class="m-r-10">Toge Inumaki</a> <span class="badge bg-green">Jobseeker</span>
                                                                                                                                                                                                                                                                                             <small class="float-right text-muted">
                                                                                                                                                                                                                                                                                                 <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                                                                                                                                                 <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                                                                                                                                                 </small>
                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                 <p class="msg">Request for Account Verification</p>
                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                  <li class="list-group-item">
                                                                                                                                                                                                                                                                                                      <div class="media">
                                                                                                                                                                                                                                                                                                          <div class="pull-left">
                                                                                                                                                                                                                                                                                                              <div class="controls">
                                                                                                                                                                                                                                                                                                                  <div class="checkbox">
                                                                                                                                                                                                                                                                                                                      <input type="checkbox" id="basic_checkbox_9"> <label for="basic_checkbox_9"></label>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                      <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                                                                                                                                                                                                                                                                                                          <i class="zmdi zmdi-star-outline"></i>
                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                           <div class="thumb hidden-sm-down m-r-20">
                                                                                                                                                                                                                                                                                                                               <img src="assets/images/xs/avatar9.jpg" class="rounded-circle" alt="">
                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                <div class="media-body">
                                                                                                                                                                                                                                                                                                                                    <div class="media-heading">
                                                                                                                                                                                                                                                                                                                                    <a href="mail-single.html" class="m-r-10">Seirin Corp.</a>
                                                                                                                                                                                                                                                                                                                                <span class="badge bg-blush">Employer</span>
                                                                                                                                                                                                                                                                                                                                <small class="float-right text-muted">
                                                                                                                                                                                                                                                                                                                                    <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                                                                                                                                                                                    <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                                                                                                                                                                                    </small>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                    <p class="msg">Request for Account Verification</p>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                     </li>
                                                                                                                                                                                                                                                                                                                                     <li class="list-group-item">
                                                                                                                                                                                                                                                                                                                                         <div class="media">
                                                                                                                                                                                                                                                                                                                                             <div class="pull-left">
                                                                                                                                                                                                                                                                                                                                                 <div class="controls">
                                                                                                                                                                                                                                                                                                                                                     <div class="checkbox">
                                                                                                                                                                                                                                                                                                                                                         <input type="checkbox" id="basic_checkbox_10"> <label for="basic_checkbox_10"></label>
                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                           <a href="javascript:void(0);" class="favourite text-muted hidden-sm-down" data-toggle="active">
                                                                                                                                                                                                                                                                                                                                                               <i class="zmdi zmdi-star-outline"></i>
                                                                                                                                                                                                                                                                                                                                                               </a>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                <div class="thumb hidden-sm-down m-r-20">
                                                                                                                                                                                                                                                                                                                                                                    <img src="assets/images/xs/avatar10.jpg" class="rounded-circle" alt="">
                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                      <div class="media-body">
                                                                                                                                                                                                                                                                                                                                                                          <div class="media-heading"> <a href="mail-single.html" class="m-r-10">Zero Two</a>
                                                                                                                                                                                                                                                                                                                                                                          <span class="badge bg-green">JobSeeker</span>
                                                                                                                                                                                                                                                                                                                                                                           <small class="float-right text-muted">
                                                                                                                                                                                                                                                                                                                                                                               <time class="hidden-sm-down" datetime="2017">12:35 AM</time>
                                                                                                                                                                                                                                                                                                                                                                               <i class="zmdi zmdi-attachment-alt"></i>
                                                                                                                                                                                                                                                                                                                                                                               </small>
                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                               <p class="msg">Request for Account Verification. </p>
                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                               </li>
                                                                                                                                                                                                                                                                                                                                                                               </ul>
                                                                                                                                                                                                                                                                                                                                                                                <div class="card m-t-5">
                                                                                                                                                                                                                                                                                                                                                                                    <div class="body">
                                                                                                                                                                                                                                                                                                                                                                                         <ul class="pagination pagination-primary m-b-0"> <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                             <a class="page-link" href="javascript:void(0);">Previous</a>
                                                                                                                                                                                                                                                                                                                                                                                             </li>
                                                                                                                                                                                                                                                                                                                                                                                             <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                                 <a class="page-link" href="javascript:void(0);">1</a>
                                                                                                                                                                                                                                                                                                                                                                                                 </li>
                                                                                                                                                                                                                                                                                                                                                                                                 <li class="page-item active">
                                                                                                                                                                                                                                                                                                                                                                                                     <a class="page-link" href="javascript:void(0);">2</a>
                                                                                                                                                                                                                                                                                                                                                                                                 </li>
                                                                                                                                                                                                                                                                                                                                                                                                 <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                                     <a class="page-link" href="javascript:void(0);">3</a>
                                                                                                                                                                                                                                                                                                                                                                                                     </li>
                                                                                                                                                                                                                                                                                                                                                                                                     <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                     </li>
                                                                                                                                                                                                                                                                                                                                                                                                     <a class="page-link" href="javascript:void(0);">Next</a>
                                                                                                                                                                                                                                                                                                                                                                                                     </li>
                                                                                                                                                                                                                                                                                                                                                                                                     </ul>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                       </section>
                                                                                                                                                                                                                                                                                                                                                                                                       </div>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
            </body>
            </html>